### ISSUE TITLE
Investigate reducing class files produced by Fields Macro

### ISSUE THREAD

**Issue by stephanh** [CommBank/maestro#317]
Currently the Fields macro produces a class for each field in a thrift structure. This can cause the number of class files to quickly blow out.

**Comment by shmookey** [comment]
The intermediate code produced by FieldsMacro constructs each Field with a getter _function_ by wrapping the getter _method_ in a closure, which generates a new class:

```scala
val foo = Field[A, B] (A.FooField.name, ((x) => x._foo));
```

Instead of constructing Field with a name and a getter function, how about we construct it with a thrift TField? The getter method can be resolved from TField.id via the thrift object's productElement() - at the cost of potentially compromising automatic type checking (it's an Any method). We wouldn't necessarily be sacrificing type _safety_ , since TField includes a type identifier, and we could give the compiler a "helping hand" here with so that users will still have strongly typed Fields.

**Comment by stephanh** [comment]
Are you able put some working sample code for how this might work forward so that we don't break backwards compatibility in how `Field` and `FieldWrapper` are used, don't loose type safety and avoid reflection if possible.

If we can't come up with a decent solution for this we might table the issue.

**Comment by shmookey** [comment]
Will do. Thinking about it a bit more, I think we should be able to subclass Function for each field type on the FieldsWrapper then create function instances for each field - we produce the same number of objects, but reduce the class output to the number of return types. It’s type safe and preserves the API, so everyone should be happy.

**Comment by shmookey** [comment]
Fixed in https://github.com/CommBank/maestro/pull/331
