### ISSUE TITLE
UploadExecution.parseHT will fail even if only one of the parsers failed

### ISSUE THREAD

**Issue by vineethvarghese** [CommBank/maestro#366]
The function : 
```scala
def parseHT[H, T](parseH: String => Result[H] = HeaderParsers.default, parseT: String => Result[T] = TrailerParsers.default)(data: DataFile): Result[(H, T)]
```
accepts 2 functions that could fail independently but the return type is just a Result. So, even if only one of those parser fail we won't be able to return a result of the other parser. During the code review, we left this in this form thinking that we will find a way to combine 2 Results. But given that that is not possible, we may need to rethink this API.

**Comment by SamRoberts** [comment]
I thought this was the desired behavior? The user has asked to get both the header and trailer data, and we can't supply them with both. My understanding during the review was that we wanted to combine both errors, rather than just reporting the first error message.

It it fairly trivial for the user to run `parseHeader` and `parseTrailer` separately.

**Comment by vineethvarghese** [comment]
Yeah we can't combine the errors, so should we have this API was more the question? We could document this fact if we think it is a reasonable approach.

**Comment by stephanh** [comment]
I don't think we need to combine errors here. You can just short circuit based on any failure.

I'm happy for it to fail unless both header and trailer parsing succeeds. @vineethvarghese what would you like to see happen in order to close this ticket?

**Comment by stephanh** [comment]
@vineethvarghese are you happy for me to close this ticket?

**Comment by vineethvarghese** [comment]
Yeah. Don't think we can do anything much.
