### ISSUE TITLE
Header and Trailer parsing for gzip files during upload

### ISSUE THREAD

**Issue by jithinjohn** [CommBank/maestro#371]
Currently header and trailer parsing is supported only for text files. We do have gzip files which are loaded as such and needs to parse header and trailer  for load assurance.

**Comment by stephanh** [comment]
@jithinjohn can you add a step to unzip the files?

**Comment by jithinjohn** [comment]
@stephanh We could do it. Are you suggesting to unzip the files before we use `upload` in our project. Also is it a work around?

**Comment by vineethvarghese** [comment]
@jithinjohn upload is pretty complicated as it is. Is this something you see in many loads?

**Comment by jithinjohn** [comment]
@vineethvarghese  For BICD we have 2 sources total of 41 files. @jonjuscorpion666 @maxmithun @snehalvidyan  Can you please comment about other loads.

**Comment by snehalvidyan** [comment]
@vineethvarghese Project loads also have one load which have zip file as input.... Nimbus Hitdata

**Comment by anandsiva** [comment]
@vineethvarghese @snehalvidyan  For nimbus hit data, we unzip and then load the data. @maxmithun Please confirm if this is the case?

**Comment by rakheshrnair** [comment]
@anandsiva @maxmithun we are currently loading the zip file as such after doing the validation for Nimbus

**Comment by vineethvarghese** [comment]
So I counted 4 loads with this need which kind of suggesst that it is not quite generic? 

Have you considered adding something to etl.util?

**Comment by stephanh** [comment]
The current plan is that you uncompress the file before parsing the header and trailer. From a performance perspective you will have to unzip the whole file anyway in order to parse the trailer.

Since we will have to support a number of different approaches such as encrypted files, gzipped files, zip files I don't think this should go into Maestro. However, etl-util might be a good place for it.
