### ISSUE TITLE
Automap macro transform function restricting number of parameters to 22

### ISSUE THREAD

**Issue by sudjam** [CommBank/maestro#384]
Automap transform function throws error when more than 22 parameters are passed to it. For 24 parameters, we get the error like "object Tuple24 is not a member of package scala".

When we tried to investigate the issue, we came across http://stackoverflow.com/questions/4152223/why-are-scala-functions-limited-to-22-parameters

Please suggest if we can have work-around.

**Comment by stephanh** [comment]
@sudjam are you able to use the transform macro instead in the mean time https://github.com/CommBank/maestro/blob/master/maestro-example/src/main/scala/au/com/cba/omnia/maestro/example/TransformExecution.scala#L56.

**Comment by stephanh** [comment]
Scala doc: https://commbank.github.io/maestro/latest/api/index.html#au.com.cba.omnia.maestro.macros.Macros$

**Comment by sudjam** [comment]
@stephanh Yes.. transform macro works. It accepts more than 22 parameters. Thanks.

**Comment by shmookey** [comment]
This issue is addressed in https://github.com/CommBank/maestro/pull/388 
Automap now uses a slightly different notation: braces instead of brackets, and no commas at the end of each rule. An example is available at https://github.com/CommBank/maestro/blob/e4834b09b46746f63d1aeaa2a67cab279003af9c/maestro-example/src/main/scala/au/com/cba/omnia/maestro/example/CustomerJob.scala
