### ISSUE TITLE
Partitioning strategy for Hive tables

### ISSUE THREAD

**Issue by anandsiva** [CommBank/maestro#420]
At the moment the hive tables are partitioned on Year,month and date columns where as end users use extract timestamp column to extract data. Some of them use between clause. We need right stratergy so that the users can access data effectively.

**Comment by rowandavies** [comment]
@anandsiva Maestro already supports arbitrary partitioning.  This might be better reported as an issue for datahub - is there something specific Maestro could better support that would help with this issue? 

Regardless, changing the partitioning will have major performance consequences.  If we increase the number of partitions it quite likely will also lead to more out of memory errors, similar to those described here:  http://www.brentozar.com/archive/2013/03/introduction-to-hive-partitioning/ 

Getting good performance for hive queries requires an understanding of partitioning - perhaps we could provide resources for learning how to optimise such things.  

Other things we could do:

1. Alter the `day` partition field to instead hold YYYYMMDD so that it is suitable using `between` directly, and similarly `month` as `YYYYMM`.  

2. Create a table `Date` with a `date` column as YYYYMMDD and `year`, `month` and `day` columns that includes, say, 1000 years, hence every date we'll ever need.  Then, joining with this table on all columns should allow dates to be selected using between and these to be mapped appropriately to select year, month and day partitions.

**Comment by stephanh** [comment]
As Rowan said Maestro already supports arbitrary partitioning. If we need to discuss the current approach to partitioning of loads in Datahub we should raise it as a Datahub issue.

**Comment by anandsiva** [comment]
Tracking this in  https://github.com/CommBank/datahub/issues/126
