### ISSUE TITLE
Support for multiple character set

### ISSUE THREAD

**Issue by anandsiva** [CommBank/maestro#425]
Requirement to support UTF character set  so that source can send and load those datasets

**Comment by jdcba** [comment]
I assume the original reason for requiring sources to be ASCII-only is due to lack of mappings from EBCDIC? Or possibly a GDW 1.0 tradition? Maestro has been filtering out any errant non-ASCII characters that might come through. It was also depending on the defaults in Cascading/Scalding.

My approach with PR#532 and PR#533 is to make reader charset explicit in the public API (converts to Java Unicode string) and provide a corresponding Unicode-capable filter.

**Comment by jdcba** [comment]
Hi all, v2.28.0 includes support for custom character sets. The Maestro legacy default (per Scalding/Cascading) remains as-is:

1. Parses UTF-8 only
2. Replaces any non-UTF-8 characters silently
3. Downselects to US-ASCII printables only

If the original source is not UTF-8 or US-ASCII, the new option `LoadConfig.charsetEncoding` can be used to resolve issues 1-2.

The new option `Clean.unicodeDefault` can be used to preserve Unicode characters during the load to resolve issue 3.
