### ISSUE TITLE
Jobs failing due to parallel load into same partition

### ISSUE THREAD

**Issue by MinuMichaelOlassayil** [CommBank/maestro#466]
Jobs failing due to parallel execution of viewHive for more than 1 files into same partition.
Job fails in local test as well as after being executed in cluster.
Project : etl.navpath-dbsa
etl-util: 1.27.0-20151203060845-a15fd45

Please find the log attached.
[dbsa_service_execution.log.zip](https://github.com/CommBank/maestro/files/51620/dbsa_service_execution.log.zip)

**Comment by sintokitteera** [comment]
If we delete partition from hdfs and if we are not deleting partition from metastore, when we run the job we are getting the same issue.("AlreadyExistsException(message:Partition already exists: Partition....")
Project : etl.farlo-clm

**Comment by rowandavies** [comment]
@sintokitteera Right, we'd expect that.  Is there a particular situation where you need to delete the directory while keeping the partition in the metastore?

**Comment by vineethvarghese** [comment]
@sintokitteera what do you expect to happen when you delete hive partitions from hdfs without notifying hive? :)

**Comment by vineethvarghese** [comment]
Did the new maestro version fix this? Please verify and close this issue if it is fixed. As a good practices, please don't leave Hive in an inconsistent state.

**Comment by vineethvarghese** [comment]
@MinuMichaelOlassayil Can you please update this?

**Comment by vineethvarghese** [comment]
Closing as there has been no response.

**Comment by sintokitteera** [comment]
@rowandavies , @vineethvarghese   I wanted to point the change found in existing behaviour of the API. Prior to the version '1.27.0-20151203060845-a15fd45' and after the next release there is no exception coming in even if we are not deleting the partition from hive metastore. Normally while rerunning our tests we never deleted the partition from metastore(if there is no schema change) since the API is taking care 
of it. I agree that deleting metastore is the good practice whenever we delete the partition from hdfs.
