### ISSUE TITLE
Usage of default AET timezone

### ISSUE THREAD

**Issue by SajeevAr** [CommBank/maestro#497]
This is related to issue #481. Opening a new issue to track this separately.

Issue: The current timezone addition provides the ability to specify timezone associated with a file during upload and hence fixes the issues in upload step. However, apart from upload, the default AET timezone was assumed in the following instances as well, which may lead to job failures.
1. Methods `byYear`, `byMonth`, `byDay`, `byHour`, `byDate` etc. in `Partition.scala` will parse the timestamp in partition field based on a given format. So `viewHive` step will fail if the timestamp is invalid in default timezone.
2. `isDate` method in `Validator.scala` will fail if timestamp in validator field is invalid in default timezone.
3. `now` method in `TimeSource.scala` also use the default timezone to generate `TimeSource`. It doesn't cause a job failure, but it restricts from creating `TimeSource` in any specific timezone.

To fix these issues, i think we can add the capability to specify desired timezone for above scenarios.

**Comment by rowandavies** [comment]
For `byYear`, `byMonth` and `byDate`, the set of valid dates is the same for every time zone, so it can stay the way it is, or always use UTC via `DateTimeFormat.forPattern(dateFormat).withZoneUTC()` or we can have a timeZone that defaults to UTC (similar to the previous timezone fix #483).

For `byHour` we could do the same, but then there's the potential for a column that is Sydney-time to be treated as UTC by not being updated.  This may be okay here though, since this isn't intended to be where we do validation of the data, and the parsed date-time is just used to extract the fields, which always exactly match the data.  I.e., we never do time zone adjustment here, this isn't the right place to do that.

`isDate` is the right place to do validation, so we should have `isDateUTC` and `isDateTZ` and require these to be used if an hour is included in the format.  Alas, I don't see a nice way to check for hours in patterns via http://joda-time.sourceforge.net/apidocs/org/joda/time/format/DateTimeFormatter.html

For the `TimeSource` `now` method, the date will be different, so we should probably always specify the timezone here - so I'm thinking there will be a new timezone argument with no default, and `nowUTC` and perhaps `nowSydney` for convenience.

Feedback welcome.

**Comment by rowandavies** [comment]
cc @AnnTomie @sibisasidharan @josephshobin

**Comment by rowandavies** [comment]
After discussing with @SajeevAr for the first part, it's not true that "it can stay the way it is" because the  format may include hours even for `byYear`, `byMonth` and `byDate`.

**Comment by rowandavies** [comment]
For `isDate` it could be better to have the timezone in the metadata in the thrift (and RDV metadata).  See: https://github.com/CommBank/datahub/issues/301
