### ISSUE TITLE
encode is not defined in au.com.cba.omnia.maestro.api

### ISSUE THREAD

**Issue by JeremyMarshall** [CommBank/maestro#502]
decode is defined

```
type Decode[A]       = au.com.cba.omnia.maestro.core.codec.Decode[A]
```

but encode is not and a user has to

```
import au.com.cba.omnia.maestro.core.codec.Encode
```

to do something like this, which pulls from a db into hdfs and hive and then out to a destination db

```
def ingestExport[T <: ThriftStruct: Decode : Encode : Tag : Manifest](
```

**Comment by rowandavies** [comment]
From memory, this was deliberate, but I may only have heard this in person.   The reason  `encode` was omitted from the api is that it's not generally what you want to do, and including it might give the impression that it was the intended way of doing things.  In the rare cases where you do want `encode` the explicit import is appropriate.

The PR and commit are:  https://github.com/CommBank/maestro/pull/146 and https://github.com/CommBank/maestro/pull/146/commits/b1f05ea7e3410c98fcbbf95d5474ab3c1ce83edd.

Note that this is not directly related to a db, hdfs or hive, it is just about scala conversions from thrift structure classes to lists of encoded string representations of their fields.  Since we normally instead write a typed form to parquet, there's usually no `encode` involved.
